name: Build and deploy
on: [push, pull_request]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Setup actions
              uses: actions/checkout@v3
              uses: actions/setup-node@v3
              with:
                  node-version: "14"
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Build and deploy
              run: yarn deploy
