name: Build and deploy
on: [push, pull_request]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Setup checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              uses: borales/actions-yarn@v3.0.0
              with:
                cmd: install
            - name: Build project
              uses: borales/actions-yarn@v3.0.0
              with:
                cmd: build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                public_dir: ./public
                public_branch: gh-pages
                cname: graph.dakskihedron.com
